### ISSUE TITLE
Elk Keypad KEYPAD 1 pressed USER_CODE_ENTERED (0) 

### ISSUE THREAD

**Issue by wappinghigh** [gwww/elkm1#82] opened 2024-09-08 03:55 UTC
what is the cause of this error clogging my log file? 
I get this error persistent every 20-30 sec
Rebooting HA, the application doesn't help 
Removing the physical keybad dosn;t help
How do I rid this behaviour?
I am running latest Elk driver and HAOS
Thanks!

**Comment by gwww** [comment] 2024-09-08 10:30
I will need a debug log to figure this one out. It doesn’t happen with my system and I’ve looked at the code and don’t see anything. 

Info on how to get a log is on the HA Elk integration page.

**Comment by wappinghigh** [comment] 2024-09-08 11:43
I added to code to configuration.yaml, rebooted  but have no idea how to find the log
Its way above my pay grade
Sorry 
Isn't there an easier way to download the log>?
Cheers

**Comment by gwww** [comment] 2024-09-08 15:25
Instructions on where the log is is on the integration page. You can attach the log the issue. 

You have a bit of time. I’m out of the country for the next two and a half weeks 😉

**Comment by wappinghigh** [comment] 2024-09-09 09:39
Where do I send the log? thanks

**Comment by wappinghigh** [comment] 2024-09-22 09:31
^ Still a problem where do I send the log?

**Comment by gwww** [comment] 2024-09-27 13:48
You can email me directly. My address is in the readme.

**Comment by wappinghigh** [comment] 2024-09-27 21:05
My apologies but I have no idea where the pyproject.toml file is located 
my email is lexbaker@me.com
can we get in contact there?
thanks

**Comment by gwww** [comment] 2024-09-28 15:13
Messages I see in the log that are meaningful are:

```
2024-09-09 19:34:40.594 DEBUG (MainThread) [elkm1_lib.connection] got_data '19KC01000000000011111110010'
2024-09-09 19:35:09.743 DEBUG (MainThread) [elkm1_lib.connection] got_data '19KC01000000000011111110010'
2024-09-09 19:35:38.693 DEBUG (MainThread) [elkm1_lib.connection] got_data '19KC01000000000011111110010'
2024-09-09 19:36:07.773 DEBUG (MainThread) [elkm1_lib.connection] got_data '19KC01000000000011111110010'
2024-09-09 19:36:36.682 DEBUG (MainThread) [elkm1_lib.connection] got_data '19KC01000000000011111110010'
```
Those messages are Keypad Change messages, sent from the panel to the integration. Decoding them, you have:
```
19 KC 01 00 000000 0 01111111 00 10

19: message length
KC: message type, which is Keypad Change message
01: keypad number 1
00: key 00, which is "no key" usually sent when a user code was sent from the keypad
000000: keypad function key illumination status (all off)
0: no code required to bypass
01111111: beep and chime mode for 8 areas (area 1 being 0, or off)
00 10: checksum
```
The only bits that are relevant are the keypad number and the key. So, every 29 seconds, keypad #1 is sending a "no key" for some reason. This probably is not normal, but I can't say for sure. The message is coming from the ElkM1 panel.

I'm not sure what to fix in the code, your panel is doing something every 29 seconds. Or something else in you network/system is sending a user code to the Elk every 29 seconds and the Elk responds with the messages you see 
above. Either way, the integration is working as intended as far as I can see from the logs.

Are you using any Elk integration service calls? Maybe in a script or an automation? I don't see anything at all being sent to the Elk in the log file, so is something outside of HA interacting with your panel?

**Comment by wappinghigh** [comment] 2024-09-29 00:43
Hi Glenn

Very appreciative of the explanation in an attempt to help me figure out whats going on 

Clearly this is not going to be easy to figure out and will be a process of exclusion 

thanks for the help

Alex

**Comment by gwww** [comment] 2024-09-30 01:46
I'm still pondering what could be causing this. In rereading the Elk protocol docs it struck me that a `KC` message like you are seeing could be caused by either changing the illumination status of one of you function keys or by changing the beep or chime mode for an area. Do you have anything that is playing with the keypad function key lights or are you changing the beep/chime mode of the keypad?

**Comment by wappinghigh** [comment] 2024-09-30 18:50
> I'm still pondering what could be causing this. In rereading the Elk protocol docs it struck me that a `KC` message like you are seeing could be caused by either changing the illumination status of one of you function keys or by changing the beep or chime mode for an area. Do you have anything that is playing with the keypad function key lights or are you changing the beep/chime mode of the keypad?

Not that I know of. Will get someone from Elk service to take a look at my panel. One of the problems with these panels as you are no doubt aware is their rudimentary software interface. It would be nice for example if there was a way to configure and manage via a web GUI.....

**Comment by wappinghigh** [comment] 2024-09-30 18:53
> FYI; I am considering a change to HA that would eliminate these messages from logbook. After looking at the code further, the code is overloading the `KC` message when a key is not pressed. The change would be to not create a logbook entry for `KC` messages with a value of 0 (`NO_KEY`). All other `KC` messages would still be added to logbook. Tagging @bdraco for his thoughts.
> 
> @wappinghigh Although this would get rid of the messages that are clogging up your logbook, you may still want to search out the root cause of why you are getting `KC` messages every 29 seconds.

I would love a HA code change to get rid of the message clogging the log book. I am still trying to get to the root cause of it. It's going to take a while though as I'm going to get a service guy to take a look and this will take time. Cheers

**Comment by wappinghigh** [comment] 2024-10-01 12:13
I stopped the Alarm error messages. It was an Alarm issue. Thanks for the help. Be happy if these sort or errors were taken out of the integration (or we had a chance in code to disable them) Appreciate all the help.

**Comment by gwww** [comment] 2024-10-01 14:29
Could you say more about how you stopped the messages. It will be useful for me (and others) if this arises again. By the way, these are not error messages, part of the functionality is to record keypad button presses in the logbook. This particular message is sent under conditions other than an actual button press. Thanks for persevering and helping to make the integration better!

**Comment by gwww** [comment] 2024-10-02 21:41
Fixed in Home Assistant by https://github.com/home-assistant/core/pull/127344

**Closed by gwww** 2024-10-02 21:41 UTC
